### ISSUE TITLE
Create function to compose an extrinsic

### ISSUE THREAD

**Issue by electronix** [scs/substrate-client#3]
Function 'compose_extrinsic'

- Action: Content of extrinsic: AccountId, Increment, Signature
- Action: encrypt payload with TEE public key
- Output: extrinsic with encrypted payload ready for transfer

**Comment by brenzi** [comment]
I'd prefer if generation of extrinsics would be done by substrate-api-client lib

**Comment by brenzi** [comment]
is part of the worker-enclave and worker-client now
